name: COMODAA Projects
favicon: null
layout_spectrum: 0.44196
typography_spectrum: 0.875
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#313133'
    - '#72767d'
    - '#b9e3ef'
    - '#ec2329'
  brandStrength: 0
  lightness: 0.75
  saturation: 1
  rhythmicContrast: 0
purpose: []
